include:
  - project: 'project-templates/ci-configurations'
    ref: main
    file: '/serverless.golang.yaml'

deploy:dev:

  only:
    - malawi-callback

deploy:prod:
  variables:
    ENVIRONMENT: prod
    AWS_PROFILE: onz
  only:
    - main
  dependencies:
    - build
