service: tnm-malawi-callback
frameworkVersion: ^3.3.0
configValidationMode: error

custom:
  functionName: ${self:service}
  functionHandler: callback
  mainSecretName: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):environment_variables.secret_name}

provider:
  name: aws
  region: eu-west-1
  stackName: ${self:custom.functionName}
  lambdaHashingVersion: "20201221"
  deploymentBucket:
    name: com.serverless.${self:provider.region}.${aws:accountId, '427246389222'}.dpo.deploys
    blockPublicAccess: true
  deploymentPrefix: dpoafrica/mno/callback
  iam:
    role:
      managedPolicies:
        - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):policy.sumo-pusher}
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource:
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.main}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.db_africainv}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.dpo_services}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.db_process}
            - ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):secrets.cache_db_process}
  apiGateway:
    restApiId: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):apiGateway.restApiId}
    restApiRootResourceId: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):apiGateway.restApiRootResourceId}
    description: Allow TNM Malawi to send callback calls

package:
  patterns:
    - "!.idea"
    - "!.serverless"
    - "!.deploy"
    - "!cache"
    - "!enums"
    - "!logger"
    - "!models"
    - "!process"
    - "!repository"
    - "!request"
    - "!utils"
    - "README.md"
    - "!sonar-project.properties"
    - "!ascii.txt"
    - "!*.go.*"
    - "!go.*"
    - "!*.go"
    - "!appspec.yml"
    - "!serverless.yml"
    - "!.gitlab-ci.yml"
    - "!.gitignore"
    - "!docker-compose.yml"
    - "!Dockerfile"
    - ${self:custom.functionHandler}

functions:
  MainFunction:
    handler: ${self:custom.functionHandler}
    name: ${self:custom.functionName}
    description: Tnm Malawi callback Lambda
    runtime: go1.x
    architecture: x86_64
    memorySize: 128
    timeout: 120
    environment:
      LOG_LEVEL: DEBUG
      SECRET_NAME: ${self:custom.mainSecretName}
      PGW_URL: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):environment_variables.pgw_url}
    vpc: ${file(./.deploy/config/${aws:accountId, '427246389222'}.yaml):vpc}
    events:
      - http:
          method: any
          path: tnm/mw/callback/{proxy+}

resources:
  Description: Built via Pipeline ID ${env:CI_PIPELINE_IID} on ${env:CI_COMMIT_BRANCH} for commit ${env:CI_COMMIT_SHORT_SHA} by ${env:CI_COMMIT_AUTHOR}
