secrets:
  main: arn:aws:secretsmanager:eu-west-1:427246389222:secret:configuration/dpo/callback/config-8PRbdm
  db_africainv: arn:aws:secretsmanager:eu-west-1:427246389222:secret:dev/dpo/africainv-kv8Bbz
  dpo_services: arn:aws:secretsmanager:eu-west-1:427246389222:secret:dev/dpo/services-rP8QsX
  db_process: arn:aws:secretsmanager:eu-west-1:427246389222:secret:configuration/process/database-1si9yj
  cache_db_process: arn:aws:secretsmanager:eu-west-1:427246389222:secret:configuration/dpo/mno/callback/cache-6h702K

environment_variables:
  secret_name: configuration/dpo/callback/config
  pgw_url: http://sergeyk-3g.dev.directpay.online/PaymentGateway/paymentGateway.php

queues:
  dpo_mail_sender: arn:aws:sqs:eu-west-1:427246389222:dpo-mail-sender

policy:
  sumo-pusher: arn:aws:iam::427246389222:policy/sumo-pusher

apiGateway:
  restApiId: snhwsehlfe
  restApiRootResourceId: cd81ifmoml


# VPC pg.dev.local
vpc:
  securityGroupIds:
    # dpo-lambda-sg
    - sg-0ee0f318f47d74b8f
    # lambda-rds-sg
    - sg-046f97274edf29070
    # dpo-lambda-redis-access
    - sg-05eed4cccc990747f
  subnetIds:
    # eu-west-1c, priv-1c
    - subnet-57dfd833
    # eu-west-1a, priv-1a
    - subnet-b18cb6c7
    # eu-west-1b, priv-1b
    - subnet-b61b58ee
